route:
  count: 4
 
 
logging:
  level:
    org.springframework.data.jpa: DEBUG
    
    
spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE    
    platform: h2

  jpa:
    generate-ddl: true
    show-sql: true

  hibernate:
    ddl-auto: create-drop    

  h2:
    console:
      enabled: true
      path: /h2-console      